<template>
    <div class="ast-explorer-root">
        <AstOptions v-model="options" />
        <div class="ast-explorer">
            <MonacoEditor v-model="yamlValue" language="yaml" />
            <MonacoEditor v-model="astJson" language="json" read-only />
        </div>
    </div>
</template>

<script>
import MonacoEditor from "./MonacoEditor.vue"
import AstOptions from "./AstOptions.vue"
import * as yamlEslintParser from "yaml-eslint-parser"

export default {
    name: "AstExplorer",
    components: { MonacoEditor, AstOptions },
    data() {
        return {
            options: {
                showLocations: false,
            },
            yamlValue: `---
# Welcome yaml-eslint-parser
message: Here you can see the AST generated by yaml-eslint-parser.
github: https://github.com/ota-meshi/yaml-eslint-parser
eslint: https://github.com/ota-meshi/eslint-plugin-yml
`,
            astJson: "",
        }
    },
    watch: {
        options: {
            handler: "refresh",
            deep: true,
        },
        yamlValue: {
            handler: "refresh",
            immediate: true,
        },
    },
    methods: {
        refresh() {
            this.astJson = JSON.stringify(
                yamlEslintParser.parseForESLint(this.yamlValue).ast,
                replacer.bind(null, this.options),
                2,
            )
        },
    },
}

/**
 * replacer for AST JSON
 */
function replacer(options, key, val) {
    if (key === "parent") {
        return undefined
    }
    if (!options.showLocations) {
        if (key === "range" || key === "loc") return undefined
    }
    return val
}
</script>

<style scoped>
.ast-explorer-root {
    min-width: 1px;
    min-height: 1px;
    display: flex;
    flex-direction: column;
    height: 100%;
}
.ast-explorer {
    min-width: 1px;
    display: flex;
    height: 100%;
}
</style>
